version: '3.1'

services:
  node-probot-bot:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always  
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: B4KB9hHhQqZ3PN5a
        MONGO_INITDB_DB_ADDRES: mongo:27017
        DB_NAME: Probot-bot
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017   
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: B4KB9hHhQqZ3PN5a
    volumes:
      - /data/db:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: B4KB9hHhQqZ3PN5a
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: t6MCRYEw2N2oPo2R