version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: B4KB9hHhQqZ3PN5a
    volumes:
      - /data/mongodb:/data/db

  express-api-base:
    build: 
      context: .
      dockerfile: ./docker/express-api-base/Dockerfile
    restart: always  
    ports:
      - "5000:5000"
    environment:
        NODE_ENV: production
        TOKEN_SECRET: wNGNTskStEo2SObvEcS93YMLQOSB4VY08C6Oej93W7kkhPJtw
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: B4KB9hHhQqZ3PN5a
        MONGO_ADDRESS: mongodb:27017
        MONGO_SSL: "false"
        MONGO_DB_NAME: Express-api
        NODE_LISTEN_ADDRESS: 0.0.0.0
        NODE_LISTEN_PORT: "5000"
    links:
        - mongodb
    volumes:
      - /data/express_api_base_logs:/usr/src/app/logs

  mongo-seed:
    build: ./docker/mongo-seed
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: B4KB9hHhQqZ3PN5a
      MONGO_ADDRESS: mongodb:27017
      MONGO_DB_NAME: Express-api

    links:
      - mongodb
